services:
  web:
    build: .
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      mydb:
        condition: service_healthy

  mydb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

