# Stage 1: Build Stage
FROM python:3.14-slim AS build

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libmariadb-dev \
    pkg-config

COPY . .

RUN pip install --prefix=/install -r requirements.txt

# Stage 2: Production Stage
FROM python:3.14-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libmariadb-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /install /usr/local
COPY --from=build /app /app

EXPOSE 5002

CMD ["python", "app.py"]